apiVersion: rds.aws.upbound.io/v1beta1
kind: Cluster
metadata:
  annotations:
    crossplane.io/composition-resource-name: rds
  generateName: platform-aws-
  labels:
    crossplane.io/composite: platform-aws
  name: platform-aws-rds
  ownerReferences:
  - apiVersion: aws.example.com/v1
    blockOwnerDeletion: true
    controller: true
    kind: XAWSInfrastructure
    name: platform-aws
    uid: ""
spec:
  forProvider:
    backupRetentionPeriod: 1
    engine: aurora-postgresql
    engineVersion: "15.4"
    masterPasswordSecretRef:
      key: password
      name: platform-aws-rds-password
      namespace: crossplane-system
    masterUsername: admin
    preferredBackupWindow: 07:00-09:00
    preferredMaintenanceWindow: sun:09:00-sun:11:00
    region: us-west-2
    vpcSecurityGroupIds:
    - sg-1234567890
